# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f rest_api/Dockerfile-installed-bionic -t sawtooth-rest-api .

# -------------=== rest api build ===-------------

FROM ubuntu:bionic as rest-api-builder

RUN apt-get update \
 && apt-get install gnupg -y

ENV VERSION=AUTO_STRICT

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get install -y -q \
    git \
    pkg-config \
    python3-aiodns \
    python3-aiohttp \
    python3-stdeb

RUN apt-get update -qq \
    && apt-get install -y -qq python3.7 python3.6

RUN rm /usr/bin/python3 \
 && ln -s /usr/bin/python3.7 /usr/bin/python3 \
 && ln -s /usr/bin/python3.7 /usr/local/bin/python3 \
 && apt-get install -y \
    python3-pip \
    python-dev \
    python3.7-dev \
    libpython3.7 \
    python3-all \
    python3-dev \
    python3-all-dev \
 && python3 -m pip install pip --upgrade

RUN python3 -m pip install --upgrade setuptools

RUN python3 -m pip install --ignore-installed \
    cchardet \
    grpcio \
    grpcio-tools \
    protobuf

RUN python3.7 -m pip install \
    pyformance \
    secp256k1 \
    netifaces

RUN python3 -m pip install \
    sawtooth-sdk

COPY . /project

RUN rm /usr/bin/python3 \
 && rm /usr/local/bin/python3 \
 && ln -s /usr/bin/python3.6 /usr/bin/python3 \
 && ln -s /usr/bin/python3.6 /usr/local/bin/python3

RUN python3 -m pip install --upgrade setuptools

RUN python3 -m pip install --ignore-installed \
    grpcio \
    grpcio-tools

RUN /project/bin/protogen

RUN cd /project/rest_api/ \
 && if [ -d "debian" ]; then rm -rf debian; fi 

RUN cd /project/rest_api/ \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && dpkg-buildpackage -b -rfakeroot -us -uc

 # -------------=== rest api docker build ===-------------
FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install -y \
 gnupg \
 systemd

COPY --from=rest-api-builder /project/python3-sawtooth-rest-api*.deb /tmp

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && dpkg -i /tmp/python3-sawtooth-*.deb || true \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 4004/tcp
EXPOSE 8008

CMD ["sawtooth-rest-api"]
