# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/authorization.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7python/sawtooth_block_info/protobuf/authorization.proto\"%\n\x11\x43onnectionRequest\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\"\xca\x02\n\x12\x43onnectionResponse\x12,\n\x05roles\x18\x01 \x03(\x0b\x32\x1d.ConnectionResponse.RoleEntry\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.ConnectionResponse.Status\x1a^\n\tRoleEntry\x12\x17\n\x04role\x18\x01 \x01(\x0e\x32\t.RoleType\x12\x38\n\tauth_type\x18\x02 \x01(\x0e\x32%.ConnectionResponse.AuthorizationType\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"K\n\x11\x41uthorizationType\x12\x1c\n\x18\x41UTHORIZATION_TYPE_UNSET\x10\x00\x12\t\n\x05TRUST\x10\x01\x12\r\n\tCHALLENGE\x10\x02\"I\n\x19\x41uthorizationTrustRequest\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType\x12\x12\n\npublic_key\x18\x02 \x01(\t\"6\n\x1a\x41uthorizationTrustResponse\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType\"6\n\x16\x41uthorizationViolation\x12\x1c\n\tviolation\x18\x01 \x01(\x0e\x32\t.RoleType\"\x1f\n\x1d\x41uthorizationChallengeRequest\"1\n\x1e\x41uthorizationChallengeResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"_\n\x1c\x41uthorizationChallengeSubmit\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x18\n\x05roles\x18\x04 \x03(\x0e\x32\t.RoleType\"8\n\x1c\x41uthorizationChallengeResult\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType*5\n\x08RoleType\x12\x13\n\x0fROLE_TYPE_UNSET\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x12\x0b\n\x07NETWORK\x10\x02\x42,\n\x15sawtooth.sdk.protobufP\x01Z\x11\x61uthorization_pb2b\x06proto3')

_ROLETYPE = DESCRIPTOR.enum_types_by_name['RoleType']
RoleType = enum_type_wrapper.EnumTypeWrapper(_ROLETYPE)
ROLE_TYPE_UNSET = 0
ALL = 1
NETWORK = 2


_CONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['ConnectionRequest']
_CONNECTIONRESPONSE = DESCRIPTOR.message_types_by_name['ConnectionResponse']
_CONNECTIONRESPONSE_ROLEENTRY = _CONNECTIONRESPONSE.nested_types_by_name['RoleEntry']
_AUTHORIZATIONTRUSTREQUEST = DESCRIPTOR.message_types_by_name['AuthorizationTrustRequest']
_AUTHORIZATIONTRUSTRESPONSE = DESCRIPTOR.message_types_by_name['AuthorizationTrustResponse']
_AUTHORIZATIONVIOLATION = DESCRIPTOR.message_types_by_name['AuthorizationViolation']
_AUTHORIZATIONCHALLENGEREQUEST = DESCRIPTOR.message_types_by_name['AuthorizationChallengeRequest']
_AUTHORIZATIONCHALLENGERESPONSE = DESCRIPTOR.message_types_by_name['AuthorizationChallengeResponse']
_AUTHORIZATIONCHALLENGESUBMIT = DESCRIPTOR.message_types_by_name['AuthorizationChallengeSubmit']
_AUTHORIZATIONCHALLENGERESULT = DESCRIPTOR.message_types_by_name['AuthorizationChallengeResult']
_CONNECTIONRESPONSE_STATUS = _CONNECTIONRESPONSE.enum_types_by_name['Status']
_CONNECTIONRESPONSE_AUTHORIZATIONTYPE = _CONNECTIONRESPONSE.enum_types_by_name['AuthorizationType']
ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionRequest)
  })
_sym_db.RegisterMessage(ConnectionRequest)

ConnectionResponse = _reflection.GeneratedProtocolMessageType('ConnectionResponse', (_message.Message,), {

  'RoleEntry' : _reflection.GeneratedProtocolMessageType('RoleEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONNECTIONRESPONSE_ROLEENTRY,
    '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
    # @@protoc_insertion_point(class_scope:ConnectionResponse.RoleEntry)
    })
  ,
  'DESCRIPTOR' : _CONNECTIONRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionResponse)
  })
_sym_db.RegisterMessage(ConnectionResponse)
_sym_db.RegisterMessage(ConnectionResponse.RoleEntry)

AuthorizationTrustRequest = _reflection.GeneratedProtocolMessageType('AuthorizationTrustRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONTRUSTREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationTrustRequest)
  })
_sym_db.RegisterMessage(AuthorizationTrustRequest)

AuthorizationTrustResponse = _reflection.GeneratedProtocolMessageType('AuthorizationTrustResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONTRUSTRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationTrustResponse)
  })
_sym_db.RegisterMessage(AuthorizationTrustResponse)

AuthorizationViolation = _reflection.GeneratedProtocolMessageType('AuthorizationViolation', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONVIOLATION,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationViolation)
  })
_sym_db.RegisterMessage(AuthorizationViolation)

AuthorizationChallengeRequest = _reflection.GeneratedProtocolMessageType('AuthorizationChallengeRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONCHALLENGEREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationChallengeRequest)
  })
_sym_db.RegisterMessage(AuthorizationChallengeRequest)

AuthorizationChallengeResponse = _reflection.GeneratedProtocolMessageType('AuthorizationChallengeResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONCHALLENGERESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationChallengeResponse)
  })
_sym_db.RegisterMessage(AuthorizationChallengeResponse)

AuthorizationChallengeSubmit = _reflection.GeneratedProtocolMessageType('AuthorizationChallengeSubmit', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONCHALLENGESUBMIT,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationChallengeSubmit)
  })
_sym_db.RegisterMessage(AuthorizationChallengeSubmit)

AuthorizationChallengeResult = _reflection.GeneratedProtocolMessageType('AuthorizationChallengeResult', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONCHALLENGERESULT,
  '__module__' : 'python.sawtooth_block_info.protobuf.authorization_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizationChallengeResult)
  })
_sym_db.RegisterMessage(AuthorizationChallengeResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\021authorization_pb2'
  _ROLETYPE._serialized_start=857
  _ROLETYPE._serialized_end=910
  _CONNECTIONREQUEST._serialized_start=59
  _CONNECTIONREQUEST._serialized_end=96
  _CONNECTIONRESPONSE._serialized_start=99
  _CONNECTIONRESPONSE._serialized_end=429
  _CONNECTIONRESPONSE_ROLEENTRY._serialized_start=211
  _CONNECTIONRESPONSE_ROLEENTRY._serialized_end=305
  _CONNECTIONRESPONSE_STATUS._serialized_start=307
  _CONNECTIONRESPONSE_STATUS._serialized_end=352
  _CONNECTIONRESPONSE_AUTHORIZATIONTYPE._serialized_start=354
  _CONNECTIONRESPONSE_AUTHORIZATIONTYPE._serialized_end=429
  _AUTHORIZATIONTRUSTREQUEST._serialized_start=431
  _AUTHORIZATIONTRUSTREQUEST._serialized_end=504
  _AUTHORIZATIONTRUSTRESPONSE._serialized_start=506
  _AUTHORIZATIONTRUSTRESPONSE._serialized_end=560
  _AUTHORIZATIONVIOLATION._serialized_start=562
  _AUTHORIZATIONVIOLATION._serialized_end=616
  _AUTHORIZATIONCHALLENGEREQUEST._serialized_start=618
  _AUTHORIZATIONCHALLENGEREQUEST._serialized_end=649
  _AUTHORIZATIONCHALLENGERESPONSE._serialized_start=651
  _AUTHORIZATIONCHALLENGERESPONSE._serialized_end=700
  _AUTHORIZATIONCHALLENGESUBMIT._serialized_start=702
  _AUTHORIZATIONCHALLENGESUBMIT._serialized_end=797
  _AUTHORIZATIONCHALLENGERESULT._serialized_start=799
  _AUTHORIZATIONCHALLENGERESULT._serialized_end=855
# @@protoc_insertion_point(module_scope)
