# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/batch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import transaction_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/python/sawtooth_block_info/protobuf/batch.proto\x1a\x35python/sawtooth_block_info/protobuf/transaction.proto\"A\n\x0b\x42\x61tchHeader\x12\x19\n\x11signer_public_key\x18\x01 \x01(\t\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\t\"d\n\x05\x42\x61tch\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x18\n\x10header_signature\x18\x02 \x01(\t\x12\"\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x0c.Transaction\x12\r\n\x05trace\x18\x04 \x01(\x08\"$\n\tBatchList\x12\x17\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x06.BatchB$\n\x15sawtooth.sdk.protobufP\x01Z\tbatch_pb2b\x06proto3')



_BATCHHEADER = DESCRIPTOR.message_types_by_name['BatchHeader']
_BATCH = DESCRIPTOR.message_types_by_name['Batch']
_BATCHLIST = DESCRIPTOR.message_types_by_name['BatchList']
BatchHeader = _reflection.GeneratedProtocolMessageType('BatchHeader', (_message.Message,), {
  'DESCRIPTOR' : _BATCHHEADER,
  '__module__' : 'python.sawtooth_block_info.protobuf.batch_pb2'
  # @@protoc_insertion_point(class_scope:BatchHeader)
  })
_sym_db.RegisterMessage(BatchHeader)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'python.sawtooth_block_info.protobuf.batch_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  })
_sym_db.RegisterMessage(Batch)

BatchList = _reflection.GeneratedProtocolMessageType('BatchList', (_message.Message,), {
  'DESCRIPTOR' : _BATCHLIST,
  '__module__' : 'python.sawtooth_block_info.protobuf.batch_pb2'
  # @@protoc_insertion_point(class_scope:BatchList)
  })
_sym_db.RegisterMessage(BatchList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\tbatch_pb2'
  _BATCHHEADER._serialized_start=106
  _BATCHHEADER._serialized_end=171
  _BATCH._serialized_start=173
  _BATCH._serialized_end=273
  _BATCHLIST._serialized_start=275
  _BATCHLIST._serialized_end=311
# @@protoc_insertion_point(module_scope)
