# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/block_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4python/sawtooth_block_info/protobuf/block_info.proto\"k\n\x0f\x42lockInfoConfig\x12\x14\n\x0clatest_block\x18\x01 \x01(\x04\x12\x14\n\x0coldest_block\x18\x02 \x01(\x04\x12\x14\n\x0ctarget_count\x18\x03 \x01(\x04\x12\x16\n\x0esync_tolerance\x18\x04 \x01(\x04\"\x81\x01\n\tBlockInfo\x12\x11\n\tblock_num\x18\x01 \x01(\x04\x12\x19\n\x11previous_block_id\x18\x02 \x01(\t\x12\x19\n\x11signer_public_key\x18\x03 \x01(\t\x12\x18\n\x10header_signature\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\"W\n\x0c\x42lockInfoTxn\x12\x19\n\x05\x62lock\x18\x01 \x01(\x0b\x32\n.BlockInfo\x12\x14\n\x0ctarget_count\x18\x02 \x01(\x04\x12\x16\n\x0esync_tolerance\x18\x03 \x01(\x04\x42\x30\n\x1csawtooth.block_info.protobufP\x01Z\x0e\x62lock_info_pb2b\x06proto3')



_BLOCKINFOCONFIG = DESCRIPTOR.message_types_by_name['BlockInfoConfig']
_BLOCKINFO = DESCRIPTOR.message_types_by_name['BlockInfo']
_BLOCKINFOTXN = DESCRIPTOR.message_types_by_name['BlockInfoTxn']
BlockInfoConfig = _reflection.GeneratedProtocolMessageType('BlockInfoConfig', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKINFOCONFIG,
  '__module__' : 'python.sawtooth_block_info.protobuf.block_info_pb2'
  # @@protoc_insertion_point(class_scope:BlockInfoConfig)
  })
_sym_db.RegisterMessage(BlockInfoConfig)

BlockInfo = _reflection.GeneratedProtocolMessageType('BlockInfo', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKINFO,
  '__module__' : 'python.sawtooth_block_info.protobuf.block_info_pb2'
  # @@protoc_insertion_point(class_scope:BlockInfo)
  })
_sym_db.RegisterMessage(BlockInfo)

BlockInfoTxn = _reflection.GeneratedProtocolMessageType('BlockInfoTxn', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKINFOTXN,
  '__module__' : 'python.sawtooth_block_info.protobuf.block_info_pb2'
  # @@protoc_insertion_point(class_scope:BlockInfoTxn)
  })
_sym_db.RegisterMessage(BlockInfoTxn)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034sawtooth.block_info.protobufP\001Z\016block_info_pb2'
  _BLOCKINFOCONFIG._serialized_start=56
  _BLOCKINFOCONFIG._serialized_end=163
  _BLOCKINFO._serialized_start=166
  _BLOCKINFO._serialized_end=295
  _BLOCKINFOTXN._serialized_start=297
  _BLOCKINFOTXN._serialized_end=384
# @@protoc_insertion_point(module_scope)
