# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_batch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import batch_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_batch__pb2
from python.sawtooth_block_info.protobuf import client_list_control_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_client__list__control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6python/sawtooth_block_info/protobuf/client_batch.proto\x1a/python/sawtooth_block_info/protobuf/batch.proto\x1a=python/sawtooth_block_info/protobuf/client_list_control.proto\"\x89\x01\n\x16\x43lientBatchListRequest\x12\x0f\n\x07head_id\x18\x01 \x01(\t\x12\x11\n\tbatch_ids\x18\x02 \x03(\t\x12%\n\x06paging\x18\x03 \x01(\x0b\x32\x15.ClientPagingControls\x12$\n\x07sorting\x18\x04 \x03(\x0b\x32\x13.ClientSortControls\"\xb7\x02\n\x17\x43lientBatchListResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientBatchListResponse.Status\x12\x17\n\x07\x62\x61tches\x18\x02 \x03(\x0b\x32\x06.Batch\x12\x0f\n\x07head_id\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingResponse\"\x99\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x12\n\x0eINVALID_PAGING\x10\x06\x12\x10\n\x0cINVALID_SORT\x10\x07\x12\x0e\n\nINVALID_ID\x10\x08\")\n\x15\x43lientBatchGetRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\"\xb8\x01\n\x16\x43lientBatchGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientBatchGetResponse.Status\x12\x15\n\x05\x62\x61tch\x18\x02 \x01(\x0b\x32\x06.Batch\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42+\n\x15sawtooth.sdk.protobufP\x01Z\x10\x63lient_batch_pb2b\x06proto3')



_CLIENTBATCHLISTREQUEST = DESCRIPTOR.message_types_by_name['ClientBatchListRequest']
_CLIENTBATCHLISTRESPONSE = DESCRIPTOR.message_types_by_name['ClientBatchListResponse']
_CLIENTBATCHGETREQUEST = DESCRIPTOR.message_types_by_name['ClientBatchGetRequest']
_CLIENTBATCHGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientBatchGetResponse']
_CLIENTBATCHLISTRESPONSE_STATUS = _CLIENTBATCHLISTRESPONSE.enum_types_by_name['Status']
_CLIENTBATCHGETRESPONSE_STATUS = _CLIENTBATCHGETRESPONSE.enum_types_by_name['Status']
ClientBatchListRequest = _reflection.GeneratedProtocolMessageType('ClientBatchListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHLISTREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchListRequest)
  })
_sym_db.RegisterMessage(ClientBatchListRequest)

ClientBatchListResponse = _reflection.GeneratedProtocolMessageType('ClientBatchListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHLISTRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchListResponse)
  })
_sym_db.RegisterMessage(ClientBatchListResponse)

ClientBatchGetRequest = _reflection.GeneratedProtocolMessageType('ClientBatchGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchGetRequest)
  })
_sym_db.RegisterMessage(ClientBatchGetRequest)

ClientBatchGetResponse = _reflection.GeneratedProtocolMessageType('ClientBatchGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchGetResponse)
  })
_sym_db.RegisterMessage(ClientBatchGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\020client_batch_pb2'
  _CLIENTBATCHLISTREQUEST._serialized_start=171
  _CLIENTBATCHLISTREQUEST._serialized_end=308
  _CLIENTBATCHLISTRESPONSE._serialized_start=311
  _CLIENTBATCHLISTRESPONSE._serialized_end=622
  _CLIENTBATCHLISTRESPONSE_STATUS._serialized_start=469
  _CLIENTBATCHLISTRESPONSE_STATUS._serialized_end=622
  _CLIENTBATCHGETREQUEST._serialized_start=624
  _CLIENTBATCHGETREQUEST._serialized_end=665
  _CLIENTBATCHGETRESPONSE._serialized_start=668
  _CLIENTBATCHGETRESPONSE._serialized_end=852
  _CLIENTBATCHGETRESPONSE_STATUS._serialized_start=765
  _CLIENTBATCHGETRESPONSE_STATUS._serialized_end=852
# @@protoc_insertion_point(module_scope)
