# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import block_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_block__pb2
from python.sawtooth_block_info.protobuf import client_list_control_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_client__list__control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6python/sawtooth_block_info/protobuf/client_block.proto\x1a/python/sawtooth_block_info/protobuf/block.proto\x1a=python/sawtooth_block_info/protobuf/client_list_control.proto\"\x89\x01\n\x16\x43lientBlockListRequest\x12\x0f\n\x07head_id\x18\x01 \x01(\t\x12\x11\n\tblock_ids\x18\x02 \x03(\t\x12%\n\x06paging\x18\x03 \x01(\x0b\x32\x15.ClientPagingControls\x12$\n\x07sorting\x18\x04 \x03(\x0b\x32\x13.ClientSortControls\"\xb6\x02\n\x17\x43lientBlockListResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientBlockListResponse.Status\x12\x16\n\x06\x62locks\x18\x02 \x03(\x0b\x32\x06.Block\x12\x0f\n\x07head_id\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingResponse\"\x99\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x12\n\x0eINVALID_PAGING\x10\x06\x12\x10\n\x0cINVALID_SORT\x10\x07\x12\x0e\n\nINVALID_ID\x10\x08\"-\n\x19\x43lientBlockGetByIdRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"/\n\x1a\x43lientBlockGetByNumRequest\x12\x11\n\tblock_num\x18\x01 \x01(\x04\">\n$ClientBlockGetByTransactionIdRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"2\n\x1e\x43lientBlockGetByBatchIdRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\"\xb8\x01\n\x16\x43lientBlockGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientBlockGetResponse.Status\x12\x15\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x06.Block\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42+\n\x15sawtooth.sdk.protobufP\x01Z\x10\x63lient_block_pb2b\x06proto3')



_CLIENTBLOCKLISTREQUEST = DESCRIPTOR.message_types_by_name['ClientBlockListRequest']
_CLIENTBLOCKLISTRESPONSE = DESCRIPTOR.message_types_by_name['ClientBlockListResponse']
_CLIENTBLOCKGETBYIDREQUEST = DESCRIPTOR.message_types_by_name['ClientBlockGetByIdRequest']
_CLIENTBLOCKGETBYNUMREQUEST = DESCRIPTOR.message_types_by_name['ClientBlockGetByNumRequest']
_CLIENTBLOCKGETBYTRANSACTIONIDREQUEST = DESCRIPTOR.message_types_by_name['ClientBlockGetByTransactionIdRequest']
_CLIENTBLOCKGETBYBATCHIDREQUEST = DESCRIPTOR.message_types_by_name['ClientBlockGetByBatchIdRequest']
_CLIENTBLOCKGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientBlockGetResponse']
_CLIENTBLOCKLISTRESPONSE_STATUS = _CLIENTBLOCKLISTRESPONSE.enum_types_by_name['Status']
_CLIENTBLOCKGETRESPONSE_STATUS = _CLIENTBLOCKGETRESPONSE.enum_types_by_name['Status']
ClientBlockListRequest = _reflection.GeneratedProtocolMessageType('ClientBlockListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKLISTREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockListRequest)
  })
_sym_db.RegisterMessage(ClientBlockListRequest)

ClientBlockListResponse = _reflection.GeneratedProtocolMessageType('ClientBlockListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKLISTRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockListResponse)
  })
_sym_db.RegisterMessage(ClientBlockListResponse)

ClientBlockGetByIdRequest = _reflection.GeneratedProtocolMessageType('ClientBlockGetByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKGETBYIDREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockGetByIdRequest)
  })
_sym_db.RegisterMessage(ClientBlockGetByIdRequest)

ClientBlockGetByNumRequest = _reflection.GeneratedProtocolMessageType('ClientBlockGetByNumRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKGETBYNUMREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockGetByNumRequest)
  })
_sym_db.RegisterMessage(ClientBlockGetByNumRequest)

ClientBlockGetByTransactionIdRequest = _reflection.GeneratedProtocolMessageType('ClientBlockGetByTransactionIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKGETBYTRANSACTIONIDREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockGetByTransactionIdRequest)
  })
_sym_db.RegisterMessage(ClientBlockGetByTransactionIdRequest)

ClientBlockGetByBatchIdRequest = _reflection.GeneratedProtocolMessageType('ClientBlockGetByBatchIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKGETBYBATCHIDREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockGetByBatchIdRequest)
  })
_sym_db.RegisterMessage(ClientBlockGetByBatchIdRequest)

ClientBlockGetResponse = _reflection.GeneratedProtocolMessageType('ClientBlockGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBLOCKGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_block_pb2'
  # @@protoc_insertion_point(class_scope:ClientBlockGetResponse)
  })
_sym_db.RegisterMessage(ClientBlockGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\020client_block_pb2'
  _CLIENTBLOCKLISTREQUEST._serialized_start=171
  _CLIENTBLOCKLISTREQUEST._serialized_end=308
  _CLIENTBLOCKLISTRESPONSE._serialized_start=311
  _CLIENTBLOCKLISTRESPONSE._serialized_end=621
  _CLIENTBLOCKLISTRESPONSE_STATUS._serialized_start=468
  _CLIENTBLOCKLISTRESPONSE_STATUS._serialized_end=621
  _CLIENTBLOCKGETBYIDREQUEST._serialized_start=623
  _CLIENTBLOCKGETBYIDREQUEST._serialized_end=668
  _CLIENTBLOCKGETBYNUMREQUEST._serialized_start=670
  _CLIENTBLOCKGETBYNUMREQUEST._serialized_end=717
  _CLIENTBLOCKGETBYTRANSACTIONIDREQUEST._serialized_start=719
  _CLIENTBLOCKGETBYTRANSACTIONIDREQUEST._serialized_end=781
  _CLIENTBLOCKGETBYBATCHIDREQUEST._serialized_start=783
  _CLIENTBLOCKGETBYBATCHIDREQUEST._serialized_end=833
  _CLIENTBLOCKGETRESPONSE._serialized_start=836
  _CLIENTBLOCKGETRESPONSE._serialized_end=1020
  _CLIENTBLOCKGETRESPONSE_STATUS._serialized_start=933
  _CLIENTBLOCKGETRESPONSE_STATUS._serialized_end=1020
# @@protoc_insertion_point(module_scope)
