# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7python/sawtooth_block_info/protobuf/client_status.proto\"\x18\n\x16\x43lientStatusGetRequest\"\xd3\x01\n\x17\x43lientStatusGetResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientStatusGetResponse.Status\x12,\n\x05peers\x18\x02 \x03(\x0b\x32\x1d.ClientStatusGetResponse.Peer\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x1a\x18\n\x04Peer\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42(\n\x15sawtooth.sdk.protobufP\x01Z\rclient_statusb\x06proto3')



_CLIENTSTATUSGETREQUEST = DESCRIPTOR.message_types_by_name['ClientStatusGetRequest']
_CLIENTSTATUSGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientStatusGetResponse']
_CLIENTSTATUSGETRESPONSE_PEER = _CLIENTSTATUSGETRESPONSE.nested_types_by_name['Peer']
_CLIENTSTATUSGETRESPONSE_STATUS = _CLIENTSTATUSGETRESPONSE.enum_types_by_name['Status']
ClientStatusGetRequest = _reflection.GeneratedProtocolMessageType('ClientStatusGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTATUSGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_status_pb2'
  # @@protoc_insertion_point(class_scope:ClientStatusGetRequest)
  })
_sym_db.RegisterMessage(ClientStatusGetRequest)

ClientStatusGetResponse = _reflection.GeneratedProtocolMessageType('ClientStatusGetResponse', (_message.Message,), {

  'Peer' : _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTSTATUSGETRESPONSE_PEER,
    '__module__' : 'python.sawtooth_block_info.protobuf.client_status_pb2'
    # @@protoc_insertion_point(class_scope:ClientStatusGetResponse.Peer)
    })
  ,
  'DESCRIPTOR' : _CLIENTSTATUSGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_status_pb2'
  # @@protoc_insertion_point(class_scope:ClientStatusGetResponse)
  })
_sym_db.RegisterMessage(ClientStatusGetResponse)
_sym_db.RegisterMessage(ClientStatusGetResponse.Peer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\rclient_status'
  _CLIENTSTATUSGETREQUEST._serialized_start=59
  _CLIENTSTATUSGETREQUEST._serialized_end=83
  _CLIENTSTATUSGETRESPONSE._serialized_start=86
  _CLIENTSTATUSGETRESPONSE._serialized_end=297
  _CLIENTSTATUSGETRESPONSE_PEER._serialized_start=226
  _CLIENTSTATUSGETRESPONSE_PEER._serialized_end=250
  _CLIENTSTATUSGETRESPONSE_STATUS._serialized_start=252
  _CLIENTSTATUSGETRESPONSE_STATUS._serialized_end=297
# @@protoc_insertion_point(module_scope)
