# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_receipt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import transaction_receipt_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_transaction__receipt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8python/sawtooth_block_info/protobuf/client_receipt.proto\x1a=python/sawtooth_block_info/protobuf/transaction_receipt.proto\"2\n\x17\x43lientReceiptGetRequest\x12\x17\n\x0ftransaction_ids\x18\x01 \x03(\t\"\xcc\x01\n\x18\x43lientReceiptGetResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ClientReceiptGetResponse.Status\x12%\n\x08receipts\x18\x02 \x03(\x0b\x32\x13.TransactionReceipt\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42-\n\x15sawtooth.sdk.protobufP\x01Z\x12\x63lient_receipt_pb2b\x06proto3')



_CLIENTRECEIPTGETREQUEST = DESCRIPTOR.message_types_by_name['ClientReceiptGetRequest']
_CLIENTRECEIPTGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientReceiptGetResponse']
_CLIENTRECEIPTGETRESPONSE_STATUS = _CLIENTRECEIPTGETRESPONSE.enum_types_by_name['Status']
ClientReceiptGetRequest = _reflection.GeneratedProtocolMessageType('ClientReceiptGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRECEIPTGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_receipt_pb2'
  # @@protoc_insertion_point(class_scope:ClientReceiptGetRequest)
  })
_sym_db.RegisterMessage(ClientReceiptGetRequest)

ClientReceiptGetResponse = _reflection.GeneratedProtocolMessageType('ClientReceiptGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRECEIPTGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_receipt_pb2'
  # @@protoc_insertion_point(class_scope:ClientReceiptGetResponse)
  })
_sym_db.RegisterMessage(ClientReceiptGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\022client_receipt_pb2'
  _CLIENTRECEIPTGETREQUEST._serialized_start=123
  _CLIENTRECEIPTGETREQUEST._serialized_end=173
  _CLIENTRECEIPTGETRESPONSE._serialized_start=176
  _CLIENTRECEIPTGETRESPONSE._serialized_end=380
  _CLIENTRECEIPTGETRESPONSE_STATUS._serialized_start=293
  _CLIENTRECEIPTGETRESPONSE_STATUS._serialized_end=380
# @@protoc_insertion_point(module_scope)
