# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_list_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=python/sawtooth_block_info/protobuf/client_list_control.proto\"4\n\x14\x43lientPagingControls\x12\r\n\x05start\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"B\n\x14\x43lientPagingResponse\x12\x0c\n\x04next\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"3\n\x12\x43lientSortControls\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x0f\n\x07reverse\x18\x02 \x01(\x08\x42\x32\n\x15sawtooth.sdk.protobufP\x01Z\x17\x63lient_list_control_pb2b\x06proto3')



_CLIENTPAGINGCONTROLS = DESCRIPTOR.message_types_by_name['ClientPagingControls']
_CLIENTPAGINGRESPONSE = DESCRIPTOR.message_types_by_name['ClientPagingResponse']
_CLIENTSORTCONTROLS = DESCRIPTOR.message_types_by_name['ClientSortControls']
ClientPagingControls = _reflection.GeneratedProtocolMessageType('ClientPagingControls', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTPAGINGCONTROLS,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_list_control_pb2'
  # @@protoc_insertion_point(class_scope:ClientPagingControls)
  })
_sym_db.RegisterMessage(ClientPagingControls)

ClientPagingResponse = _reflection.GeneratedProtocolMessageType('ClientPagingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTPAGINGRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_list_control_pb2'
  # @@protoc_insertion_point(class_scope:ClientPagingResponse)
  })
_sym_db.RegisterMessage(ClientPagingResponse)

ClientSortControls = _reflection.GeneratedProtocolMessageType('ClientSortControls', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSORTCONTROLS,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_list_control_pb2'
  # @@protoc_insertion_point(class_scope:ClientSortControls)
  })
_sym_db.RegisterMessage(ClientSortControls)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\027client_list_control_pb2'
  _CLIENTPAGINGCONTROLS._serialized_start=65
  _CLIENTPAGINGCONTROLS._serialized_end=117
  _CLIENTPAGINGRESPONSE._serialized_start=119
  _CLIENTPAGINGRESPONSE._serialized_end=185
  _CLIENTSORTCONTROLS._serialized_start=187
  _CLIENTSORTCONTROLS._serialized_end=238
# @@protoc_insertion_point(module_scope)
