# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_peers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6python/sawtooth_block_info/protobuf/client_peers.proto\"\x17\n\x15\x43lientPeersGetRequest\"\x86\x01\n\x16\x43lientPeersGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientPeersGetResponse.Status\x12\r\n\x05peers\x18\x02 \x03(\t\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42&\n\x15sawtooth.sdk.protobufP\x01Z\x0b\x63lient_peerb\x06proto3')



_CLIENTPEERSGETREQUEST = DESCRIPTOR.message_types_by_name['ClientPeersGetRequest']
_CLIENTPEERSGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientPeersGetResponse']
_CLIENTPEERSGETRESPONSE_STATUS = _CLIENTPEERSGETRESPONSE.enum_types_by_name['Status']
ClientPeersGetRequest = _reflection.GeneratedProtocolMessageType('ClientPeersGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTPEERSGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_peers_pb2'
  # @@protoc_insertion_point(class_scope:ClientPeersGetRequest)
  })
_sym_db.RegisterMessage(ClientPeersGetRequest)

ClientPeersGetResponse = _reflection.GeneratedProtocolMessageType('ClientPeersGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTPEERSGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_peers_pb2'
  # @@protoc_insertion_point(class_scope:ClientPeersGetResponse)
  })
_sym_db.RegisterMessage(ClientPeersGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\013client_peer'
  _CLIENTPEERSGETREQUEST._serialized_start=58
  _CLIENTPEERSGETREQUEST._serialized_end=81
  _CLIENTPEERSGETRESPONSE._serialized_start=84
  _CLIENTPEERSGETRESPONSE._serialized_end=218
  _CLIENTPEERSGETRESPONSE_STATUS._serialized_start=173
  _CLIENTPEERSGETRESPONSE_STATUS._serialized_end=218
# @@protoc_insertion_point(module_scope)
