# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import events_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6python/sawtooth_block_info/protobuf/client_event.proto\x1a\x30python/sawtooth_block_info/protobuf/events.proto\"g\n\x1c\x43lientEventsSubscribeRequest\x12)\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x12.EventSubscription\x12\x1c\n\x14last_known_block_ids\x18\x02 \x03(\t\"\xbb\x01\n\x1d\x43lientEventsSubscribeResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.ClientEventsSubscribeResponse.Status\x12\x18\n\x10response_message\x18\x02 \x01(\t\"I\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINVALID_FILTER\x10\x02\x12\x11\n\rUNKNOWN_BLOCK\x10\x03\" \n\x1e\x43lientEventsUnsubscribeRequest\"\x92\x01\n\x1f\x43lientEventsUnsubscribeResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.ClientEventsUnsubscribeResponse.Status\"6\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\"V\n\x16\x43lientEventsGetRequest\x12)\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x12.EventSubscription\x12\x11\n\tblock_ids\x18\x02 \x03(\t\"\xc1\x01\n\x17\x43lientEventsGetResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientEventsGetResponse.Status\x12\x16\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x06.Event\"]\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x12\n\x0eINVALID_FILTER\x10\x03\x12\x11\n\rUNKNOWN_BLOCK\x10\x04\x42+\n\x15sawtooth.sdk.protobufP\x01Z\x10\x63lient_event_pb2b\x06proto3')



_CLIENTEVENTSSUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['ClientEventsSubscribeRequest']
_CLIENTEVENTSSUBSCRIBERESPONSE = DESCRIPTOR.message_types_by_name['ClientEventsSubscribeResponse']
_CLIENTEVENTSUNSUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['ClientEventsUnsubscribeRequest']
_CLIENTEVENTSUNSUBSCRIBERESPONSE = DESCRIPTOR.message_types_by_name['ClientEventsUnsubscribeResponse']
_CLIENTEVENTSGETREQUEST = DESCRIPTOR.message_types_by_name['ClientEventsGetRequest']
_CLIENTEVENTSGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientEventsGetResponse']
_CLIENTEVENTSSUBSCRIBERESPONSE_STATUS = _CLIENTEVENTSSUBSCRIBERESPONSE.enum_types_by_name['Status']
_CLIENTEVENTSUNSUBSCRIBERESPONSE_STATUS = _CLIENTEVENTSUNSUBSCRIBERESPONSE.enum_types_by_name['Status']
_CLIENTEVENTSGETRESPONSE_STATUS = _CLIENTEVENTSGETRESPONSE.enum_types_by_name['Status']
ClientEventsSubscribeRequest = _reflection.GeneratedProtocolMessageType('ClientEventsSubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSSUBSCRIBEREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsSubscribeRequest)
  })
_sym_db.RegisterMessage(ClientEventsSubscribeRequest)

ClientEventsSubscribeResponse = _reflection.GeneratedProtocolMessageType('ClientEventsSubscribeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSSUBSCRIBERESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsSubscribeResponse)
  })
_sym_db.RegisterMessage(ClientEventsSubscribeResponse)

ClientEventsUnsubscribeRequest = _reflection.GeneratedProtocolMessageType('ClientEventsUnsubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSUNSUBSCRIBEREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsUnsubscribeRequest)
  })
_sym_db.RegisterMessage(ClientEventsUnsubscribeRequest)

ClientEventsUnsubscribeResponse = _reflection.GeneratedProtocolMessageType('ClientEventsUnsubscribeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSUNSUBSCRIBERESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsUnsubscribeResponse)
  })
_sym_db.RegisterMessage(ClientEventsUnsubscribeResponse)

ClientEventsGetRequest = _reflection.GeneratedProtocolMessageType('ClientEventsGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsGetRequest)
  })
_sym_db.RegisterMessage(ClientEventsGetRequest)

ClientEventsGetResponse = _reflection.GeneratedProtocolMessageType('ClientEventsGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEVENTSGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_event_pb2'
  # @@protoc_insertion_point(class_scope:ClientEventsGetResponse)
  })
_sym_db.RegisterMessage(ClientEventsGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\020client_event_pb2'
  _CLIENTEVENTSSUBSCRIBEREQUEST._serialized_start=108
  _CLIENTEVENTSSUBSCRIBEREQUEST._serialized_end=211
  _CLIENTEVENTSSUBSCRIBERESPONSE._serialized_start=214
  _CLIENTEVENTSSUBSCRIBERESPONSE._serialized_end=401
  _CLIENTEVENTSSUBSCRIBERESPONSE_STATUS._serialized_start=328
  _CLIENTEVENTSSUBSCRIBERESPONSE_STATUS._serialized_end=401
  _CLIENTEVENTSUNSUBSCRIBEREQUEST._serialized_start=403
  _CLIENTEVENTSUNSUBSCRIBEREQUEST._serialized_end=435
  _CLIENTEVENTSUNSUBSCRIBERESPONSE._serialized_start=438
  _CLIENTEVENTSUNSUBSCRIBERESPONSE._serialized_end=584
  _CLIENTEVENTSUNSUBSCRIBERESPONSE_STATUS._serialized_start=530
  _CLIENTEVENTSUNSUBSCRIBERESPONSE_STATUS._serialized_end=584
  _CLIENTEVENTSGETREQUEST._serialized_start=586
  _CLIENTEVENTSGETREQUEST._serialized_end=672
  _CLIENTEVENTSGETRESPONSE._serialized_start=675
  _CLIENTEVENTSGETRESPONSE._serialized_end=868
  _CLIENTEVENTSGETRESPONSE_STATUS._serialized_start=775
  _CLIENTEVENTSGETRESPONSE_STATUS._serialized_end=868
# @@protoc_insertion_point(module_scope)
