# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import transaction_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_transaction__pb2
from python.sawtooth_block_info.protobuf import client_list_control_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_client__list__control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<python/sawtooth_block_info/protobuf/client_transaction.proto\x1a\x35python/sawtooth_block_info/protobuf/transaction.proto\x1a=python/sawtooth_block_info/protobuf/client_list_control.proto\"\x95\x01\n\x1c\x43lientTransactionListRequest\x12\x0f\n\x07head_id\x18\x01 \x01(\t\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\t\x12%\n\x06paging\x18\x03 \x01(\x0b\x32\x15.ClientPagingControls\x12$\n\x07sorting\x18\x04 \x03(\x0b\x32\x13.ClientSortControls\"\xce\x02\n\x1d\x43lientTransactionListResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.ClientTransactionListResponse.Status\x12\"\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x0c.Transaction\x12\x0f\n\x07head_id\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingResponse\"\x99\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x12\n\x0eINVALID_PAGING\x10\x06\x12\x10\n\x0cINVALID_SORT\x10\x07\x12\x0e\n\nINVALID_ID\x10\x08\"5\n\x1b\x43lientTransactionGetRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\xd0\x01\n\x1c\x43lientTransactionGetResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.ClientTransactionGetResponse.Status\x12!\n\x0btransaction\x18\x02 \x01(\x0b\x32\x0c.Transaction\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42\x31\n\x15sawtooth.sdk.protobufP\x01Z\x16\x63lient_transaction_pb2b\x06proto3')



_CLIENTTRANSACTIONLISTREQUEST = DESCRIPTOR.message_types_by_name['ClientTransactionListRequest']
_CLIENTTRANSACTIONLISTRESPONSE = DESCRIPTOR.message_types_by_name['ClientTransactionListResponse']
_CLIENTTRANSACTIONGETREQUEST = DESCRIPTOR.message_types_by_name['ClientTransactionGetRequest']
_CLIENTTRANSACTIONGETRESPONSE = DESCRIPTOR.message_types_by_name['ClientTransactionGetResponse']
_CLIENTTRANSACTIONLISTRESPONSE_STATUS = _CLIENTTRANSACTIONLISTRESPONSE.enum_types_by_name['Status']
_CLIENTTRANSACTIONGETRESPONSE_STATUS = _CLIENTTRANSACTIONGETRESPONSE.enum_types_by_name['Status']
ClientTransactionListRequest = _reflection.GeneratedProtocolMessageType('ClientTransactionListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTRANSACTIONLISTREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_transaction_pb2'
  # @@protoc_insertion_point(class_scope:ClientTransactionListRequest)
  })
_sym_db.RegisterMessage(ClientTransactionListRequest)

ClientTransactionListResponse = _reflection.GeneratedProtocolMessageType('ClientTransactionListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTRANSACTIONLISTRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_transaction_pb2'
  # @@protoc_insertion_point(class_scope:ClientTransactionListResponse)
  })
_sym_db.RegisterMessage(ClientTransactionListResponse)

ClientTransactionGetRequest = _reflection.GeneratedProtocolMessageType('ClientTransactionGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTRANSACTIONGETREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_transaction_pb2'
  # @@protoc_insertion_point(class_scope:ClientTransactionGetRequest)
  })
_sym_db.RegisterMessage(ClientTransactionGetRequest)

ClientTransactionGetResponse = _reflection.GeneratedProtocolMessageType('ClientTransactionGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTRANSACTIONGETRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_transaction_pb2'
  # @@protoc_insertion_point(class_scope:ClientTransactionGetResponse)
  })
_sym_db.RegisterMessage(ClientTransactionGetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\026client_transaction_pb2'
  _CLIENTTRANSACTIONLISTREQUEST._serialized_start=183
  _CLIENTTRANSACTIONLISTREQUEST._serialized_end=332
  _CLIENTTRANSACTIONLISTRESPONSE._serialized_start=335
  _CLIENTTRANSACTIONLISTRESPONSE._serialized_end=669
  _CLIENTTRANSACTIONLISTRESPONSE_STATUS._serialized_start=516
  _CLIENTTRANSACTIONLISTRESPONSE_STATUS._serialized_end=669
  _CLIENTTRANSACTIONGETREQUEST._serialized_start=671
  _CLIENTTRANSACTIONGETREQUEST._serialized_end=724
  _CLIENTTRANSACTIONGETRESPONSE._serialized_start=727
  _CLIENTTRANSACTIONGETRESPONSE._serialized_end=935
  _CLIENTTRANSACTIONGETRESPONSE_STATUS._serialized_start=848
  _CLIENTTRANSACTIONGETRESPONSE_STATUS._serialized_end=935
# @@protoc_insertion_point(module_scope)
