# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/client_batch_submit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import batch_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_batch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=python/sawtooth_block_info/protobuf/client_batch_submit.proto\x1a/python/sawtooth_block_info/protobuf/batch.proto\"\xbd\x02\n\x11\x43lientBatchStatus\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12)\n\x06status\x18\x02 \x01(\x0e\x32\x19.ClientBatchStatus.Status\x12\x43\n\x14invalid_transactions\x18\x03 \x03(\x0b\x32%.ClientBatchStatus.InvalidTransaction\x1aT\n\x12InvalidTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rextended_data\x18\x03 \x01(\x0c\"P\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\r\n\tCOMMITTED\x10\x01\x12\x0b\n\x07INVALID\x10\x02\x12\x0b\n\x07PENDING\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\"3\n\x18\x43lientBatchSubmitRequest\x12\x17\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x06.Batch\"\xa9\x01\n\x19\x43lientBatchSubmitResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.ClientBatchSubmitResponse.Status\"Y\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x11\n\rINVALID_BATCH\x10\x03\x12\x0e\n\nQUEUE_FULL\x10\x04\"L\n\x18\x43lientBatchStatusRequest\x12\x11\n\tbatch_ids\x18\x01 \x03(\t\x12\x0c\n\x04wait\x18\x02 \x01(\x08\x12\x0f\n\x07timeout\x18\x03 \x01(\r\"\xd3\x01\n\x19\x43lientBatchStatusResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.ClientBatchStatusResponse.Status\x12*\n\x0e\x62\x61tch_statuses\x18\x02 \x03(\x0b\x32\x12.ClientBatchStatus\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42\x32\n\x15sawtooth.sdk.protobufP\x01Z\x17\x63lient_batch_submit_pb2b\x06proto3')



_CLIENTBATCHSTATUS = DESCRIPTOR.message_types_by_name['ClientBatchStatus']
_CLIENTBATCHSTATUS_INVALIDTRANSACTION = _CLIENTBATCHSTATUS.nested_types_by_name['InvalidTransaction']
_CLIENTBATCHSUBMITREQUEST = DESCRIPTOR.message_types_by_name['ClientBatchSubmitRequest']
_CLIENTBATCHSUBMITRESPONSE = DESCRIPTOR.message_types_by_name['ClientBatchSubmitResponse']
_CLIENTBATCHSTATUSREQUEST = DESCRIPTOR.message_types_by_name['ClientBatchStatusRequest']
_CLIENTBATCHSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['ClientBatchStatusResponse']
_CLIENTBATCHSTATUS_STATUS = _CLIENTBATCHSTATUS.enum_types_by_name['Status']
_CLIENTBATCHSUBMITRESPONSE_STATUS = _CLIENTBATCHSUBMITRESPONSE.enum_types_by_name['Status']
_CLIENTBATCHSTATUSRESPONSE_STATUS = _CLIENTBATCHSTATUSRESPONSE.enum_types_by_name['Status']
ClientBatchStatus = _reflection.GeneratedProtocolMessageType('ClientBatchStatus', (_message.Message,), {

  'InvalidTransaction' : _reflection.GeneratedProtocolMessageType('InvalidTransaction', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTBATCHSTATUS_INVALIDTRANSACTION,
    '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
    # @@protoc_insertion_point(class_scope:ClientBatchStatus.InvalidTransaction)
    })
  ,
  'DESCRIPTOR' : _CLIENTBATCHSTATUS,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchStatus)
  })
_sym_db.RegisterMessage(ClientBatchStatus)
_sym_db.RegisterMessage(ClientBatchStatus.InvalidTransaction)

ClientBatchSubmitRequest = _reflection.GeneratedProtocolMessageType('ClientBatchSubmitRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHSUBMITREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchSubmitRequest)
  })
_sym_db.RegisterMessage(ClientBatchSubmitRequest)

ClientBatchSubmitResponse = _reflection.GeneratedProtocolMessageType('ClientBatchSubmitResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHSUBMITRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchSubmitResponse)
  })
_sym_db.RegisterMessage(ClientBatchSubmitResponse)

ClientBatchStatusRequest = _reflection.GeneratedProtocolMessageType('ClientBatchStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHSTATUSREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchStatusRequest)
  })
_sym_db.RegisterMessage(ClientBatchStatusRequest)

ClientBatchStatusResponse = _reflection.GeneratedProtocolMessageType('ClientBatchStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTBATCHSTATUSRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.client_batch_submit_pb2'
  # @@protoc_insertion_point(class_scope:ClientBatchStatusResponse)
  })
_sym_db.RegisterMessage(ClientBatchStatusResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\027client_batch_submit_pb2'
  _CLIENTBATCHSTATUS._serialized_start=115
  _CLIENTBATCHSTATUS._serialized_end=432
  _CLIENTBATCHSTATUS_INVALIDTRANSACTION._serialized_start=266
  _CLIENTBATCHSTATUS_INVALIDTRANSACTION._serialized_end=350
  _CLIENTBATCHSTATUS_STATUS._serialized_start=352
  _CLIENTBATCHSTATUS_STATUS._serialized_end=432
  _CLIENTBATCHSUBMITREQUEST._serialized_start=434
  _CLIENTBATCHSUBMITREQUEST._serialized_end=485
  _CLIENTBATCHSUBMITRESPONSE._serialized_start=488
  _CLIENTBATCHSUBMITRESPONSE._serialized_end=657
  _CLIENTBATCHSUBMITRESPONSE_STATUS._serialized_start=568
  _CLIENTBATCHSUBMITRESPONSE_STATUS._serialized_end=657
  _CLIENTBATCHSTATUSREQUEST._serialized_start=659
  _CLIENTBATCHSTATUSREQUEST._serialized_end=735
  _CLIENTBATCHSTATUSRESPONSE._serialized_start=738
  _CLIENTBATCHSTATUSRESPONSE._serialized_end=949
  _CLIENTBATCHSTATUSRESPONSE_STATUS._serialized_start=862
  _CLIENTBATCHSTATUSRESPONSE_STATUS._serialized_end=949
# @@protoc_insertion_point(module_scope)
