# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0python/sawtooth_block_info/protobuf/events.proto\"x\n\x05\x45vent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12$\n\nattributes\x18\x02 \x03(\x0b\x32\x10.Event.Attribute\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x1a\'\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"#\n\tEventList\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event\"\xc1\x01\n\x0b\x45ventFilter\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0cmatch_string\x18\x02 \x01(\t\x12,\n\x0b\x66ilter_type\x18\x03 \x01(\x0e\x32\x17.EventFilter.FilterType\"a\n\nFilterType\x12\x15\n\x11\x46ILTER_TYPE_UNSET\x10\x00\x12\x0e\n\nSIMPLE_ANY\x10\x01\x12\x0e\n\nSIMPLE_ALL\x10\x02\x12\r\n\tREGEX_ANY\x10\x03\x12\r\n\tREGEX_ALL\x10\x04\"F\n\x11\x45ventSubscription\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x1d\n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x0c.EventFilterB%\n\x15sawtooth.sdk.protobufP\x01Z\nevents_pb2b\x06proto3')



_EVENT = DESCRIPTOR.message_types_by_name['Event']
_EVENT_ATTRIBUTE = _EVENT.nested_types_by_name['Attribute']
_EVENTLIST = DESCRIPTOR.message_types_by_name['EventList']
_EVENTFILTER = DESCRIPTOR.message_types_by_name['EventFilter']
_EVENTSUBSCRIPTION = DESCRIPTOR.message_types_by_name['EventSubscription']
_EVENTFILTER_FILTERTYPE = _EVENTFILTER.enum_types_by_name['FilterType']
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'Attribute' : _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_ATTRIBUTE,
    '__module__' : 'python.sawtooth_block_info.protobuf.events_pb2'
    # @@protoc_insertion_point(class_scope:Event.Attribute)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'python.sawtooth_block_info.protobuf.events_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.Attribute)

EventList = _reflection.GeneratedProtocolMessageType('EventList', (_message.Message,), {
  'DESCRIPTOR' : _EVENTLIST,
  '__module__' : 'python.sawtooth_block_info.protobuf.events_pb2'
  # @@protoc_insertion_point(class_scope:EventList)
  })
_sym_db.RegisterMessage(EventList)

EventFilter = _reflection.GeneratedProtocolMessageType('EventFilter', (_message.Message,), {
  'DESCRIPTOR' : _EVENTFILTER,
  '__module__' : 'python.sawtooth_block_info.protobuf.events_pb2'
  # @@protoc_insertion_point(class_scope:EventFilter)
  })
_sym_db.RegisterMessage(EventFilter)

EventSubscription = _reflection.GeneratedProtocolMessageType('EventSubscription', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSUBSCRIPTION,
  '__module__' : 'python.sawtooth_block_info.protobuf.events_pb2'
  # @@protoc_insertion_point(class_scope:EventSubscription)
  })
_sym_db.RegisterMessage(EventSubscription)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\nevents_pb2'
  _EVENT._serialized_start=52
  _EVENT._serialized_end=172
  _EVENT_ATTRIBUTE._serialized_start=133
  _EVENT_ATTRIBUTE._serialized_end=172
  _EVENTLIST._serialized_start=174
  _EVENTLIST._serialized_end=209
  _EVENTFILTER._serialized_start=212
  _EVENTFILTER._serialized_end=405
  _EVENTFILTER_FILTERTYPE._serialized_start=308
  _EVENTFILTER_FILTERTYPE._serialized_end=405
  _EVENTSUBSCRIPTION._serialized_start=407
  _EVENTSUBSCRIPTION._serialized_end=477
# @@protoc_insertion_point(module_scope)
