# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/merkle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0python/sawtooth_block_info/protobuf/merkle.proto\"\x95\x01\n\x0e\x43hangeLogEntry\x12\x0e\n\x06parent\x18\x01 \x01(\x0c\x12\x11\n\tadditions\x18\x02 \x03(\x0c\x12-\n\nsuccessors\x18\x03 \x03(\x0b\x32\x19.ChangeLogEntry.Successor\x1a\x31\n\tSuccessor\x12\x11\n\tsuccessor\x18\x01 \x01(\x0c\x12\x11\n\tdeletions\x18\x02 \x03(\x0c\x42%\n\x15sawtooth.sdk.protobufP\x01Z\nmerkle_pb2b\x06proto3')



_CHANGELOGENTRY = DESCRIPTOR.message_types_by_name['ChangeLogEntry']
_CHANGELOGENTRY_SUCCESSOR = _CHANGELOGENTRY.nested_types_by_name['Successor']
ChangeLogEntry = _reflection.GeneratedProtocolMessageType('ChangeLogEntry', (_message.Message,), {

  'Successor' : _reflection.GeneratedProtocolMessageType('Successor', (_message.Message,), {
    'DESCRIPTOR' : _CHANGELOGENTRY_SUCCESSOR,
    '__module__' : 'python.sawtooth_block_info.protobuf.merkle_pb2'
    # @@protoc_insertion_point(class_scope:ChangeLogEntry.Successor)
    })
  ,
  'DESCRIPTOR' : _CHANGELOGENTRY,
  '__module__' : 'python.sawtooth_block_info.protobuf.merkle_pb2'
  # @@protoc_insertion_point(class_scope:ChangeLogEntry)
  })
_sym_db.RegisterMessage(ChangeLogEntry)
_sym_db.RegisterMessage(ChangeLogEntry.Successor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\nmerkle_pb2'
  _CHANGELOGENTRY._serialized_start=53
  _CHANGELOGENTRY._serialized_end=202
  _CHANGELOGENTRY_SUCCESSOR._serialized_start=153
  _CHANGELOGENTRY_SUCCESSOR._serialized_end=202
# @@protoc_insertion_point(module_scope)
