# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1python/sawtooth_block_info/protobuf/network.proto\"\x13\n\x11\x44isconnectMessage\"A\n\x13PeerRegisterRequest\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x18\n\x10protocol_version\x18\x02 \x01(\r\"\x17\n\x15PeerUnregisterRequest\"\x11\n\x0fGetPeersRequest\"*\n\x10GetPeersResponse\x12\x16\n\x0epeer_endpoints\x18\x01 \x03(\t\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"\xb4\x01\n\rGossipMessage\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x30\n\x0c\x63ontent_type\x18\x02 \x01(\x0e\x32\x1a.GossipMessage.ContentType\x12\x14\n\x0ctime_to_live\x18\x03 \x01(\r\"J\n\x0b\x43ontentType\x12\x16\n\x12\x43ONTENT_TYPE_UNSET\x10\x00\x12\t\n\x05\x42LOCK\x10\x01\x12\t\n\x05\x42\x41TCH\x10\x02\x12\r\n\tCONSENSUS\x10\x03\"w\n\x16NetworkAcknowledgement\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.NetworkAcknowledgement.Status\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"K\n\x12GossipBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x14\n\x0ctime_to_live\x18\x03 \x01(\r\"&\n\x13GossipBlockResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"&\n\x13GossipBatchResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"N\n\x1bGossipBatchByBatchIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x14\n\x0ctime_to_live\x18\x03 \x01(\r\"U\n!GossipBatchByTransactionIdRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x14\n\x0ctime_to_live\x18\x03 \x01(\rB&\n\x15sawtooth.sdk.protobufP\x01Z\x0bnetwork_pb2b\x06proto3')



_DISCONNECTMESSAGE = DESCRIPTOR.message_types_by_name['DisconnectMessage']
_PEERREGISTERREQUEST = DESCRIPTOR.message_types_by_name['PeerRegisterRequest']
_PEERUNREGISTERREQUEST = DESCRIPTOR.message_types_by_name['PeerUnregisterRequest']
_GETPEERSREQUEST = DESCRIPTOR.message_types_by_name['GetPeersRequest']
_GETPEERSRESPONSE = DESCRIPTOR.message_types_by_name['GetPeersResponse']
_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PINGRESPONSE = DESCRIPTOR.message_types_by_name['PingResponse']
_GOSSIPMESSAGE = DESCRIPTOR.message_types_by_name['GossipMessage']
_NETWORKACKNOWLEDGEMENT = DESCRIPTOR.message_types_by_name['NetworkAcknowledgement']
_GOSSIPBLOCKREQUEST = DESCRIPTOR.message_types_by_name['GossipBlockRequest']
_GOSSIPBLOCKRESPONSE = DESCRIPTOR.message_types_by_name['GossipBlockResponse']
_GOSSIPBATCHRESPONSE = DESCRIPTOR.message_types_by_name['GossipBatchResponse']
_GOSSIPBATCHBYBATCHIDREQUEST = DESCRIPTOR.message_types_by_name['GossipBatchByBatchIdRequest']
_GOSSIPBATCHBYTRANSACTIONIDREQUEST = DESCRIPTOR.message_types_by_name['GossipBatchByTransactionIdRequest']
_GOSSIPMESSAGE_CONTENTTYPE = _GOSSIPMESSAGE.enum_types_by_name['ContentType']
_NETWORKACKNOWLEDGEMENT_STATUS = _NETWORKACKNOWLEDGEMENT.enum_types_by_name['Status']
DisconnectMessage = _reflection.GeneratedProtocolMessageType('DisconnectMessage', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTMESSAGE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectMessage)
  })
_sym_db.RegisterMessage(DisconnectMessage)

PeerRegisterRequest = _reflection.GeneratedProtocolMessageType('PeerRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEERREGISTERREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:PeerRegisterRequest)
  })
_sym_db.RegisterMessage(PeerRegisterRequest)

PeerUnregisterRequest = _reflection.GeneratedProtocolMessageType('PeerUnregisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEERUNREGISTERREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:PeerUnregisterRequest)
  })
_sym_db.RegisterMessage(PeerUnregisterRequest)

GetPeersRequest = _reflection.GeneratedProtocolMessageType('GetPeersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPEERSREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GetPeersRequest)
  })
_sym_db.RegisterMessage(GetPeersRequest)

GetPeersResponse = _reflection.GeneratedProtocolMessageType('GetPeersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPEERSRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GetPeersResponse)
  })
_sym_db.RegisterMessage(GetPeersResponse)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

GossipMessage = _reflection.GeneratedProtocolMessageType('GossipMessage', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPMESSAGE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipMessage)
  })
_sym_db.RegisterMessage(GossipMessage)

NetworkAcknowledgement = _reflection.GeneratedProtocolMessageType('NetworkAcknowledgement', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKACKNOWLEDGEMENT,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:NetworkAcknowledgement)
  })
_sym_db.RegisterMessage(NetworkAcknowledgement)

GossipBlockRequest = _reflection.GeneratedProtocolMessageType('GossipBlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPBLOCKREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipBlockRequest)
  })
_sym_db.RegisterMessage(GossipBlockRequest)

GossipBlockResponse = _reflection.GeneratedProtocolMessageType('GossipBlockResponse', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPBLOCKRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipBlockResponse)
  })
_sym_db.RegisterMessage(GossipBlockResponse)

GossipBatchResponse = _reflection.GeneratedProtocolMessageType('GossipBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPBATCHRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipBatchResponse)
  })
_sym_db.RegisterMessage(GossipBatchResponse)

GossipBatchByBatchIdRequest = _reflection.GeneratedProtocolMessageType('GossipBatchByBatchIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPBATCHBYBATCHIDREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipBatchByBatchIdRequest)
  })
_sym_db.RegisterMessage(GossipBatchByBatchIdRequest)

GossipBatchByTransactionIdRequest = _reflection.GeneratedProtocolMessageType('GossipBatchByTransactionIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIPBATCHBYTRANSACTIONIDREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.network_pb2'
  # @@protoc_insertion_point(class_scope:GossipBatchByTransactionIdRequest)
  })
_sym_db.RegisterMessage(GossipBatchByTransactionIdRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\013network_pb2'
  _DISCONNECTMESSAGE._serialized_start=53
  _DISCONNECTMESSAGE._serialized_end=72
  _PEERREGISTERREQUEST._serialized_start=74
  _PEERREGISTERREQUEST._serialized_end=139
  _PEERUNREGISTERREQUEST._serialized_start=141
  _PEERUNREGISTERREQUEST._serialized_end=164
  _GETPEERSREQUEST._serialized_start=166
  _GETPEERSREQUEST._serialized_end=183
  _GETPEERSRESPONSE._serialized_start=185
  _GETPEERSRESPONSE._serialized_end=227
  _PINGREQUEST._serialized_start=229
  _PINGREQUEST._serialized_end=242
  _PINGRESPONSE._serialized_start=244
  _PINGRESPONSE._serialized_end=258
  _GOSSIPMESSAGE._serialized_start=261
  _GOSSIPMESSAGE._serialized_end=441
  _GOSSIPMESSAGE_CONTENTTYPE._serialized_start=367
  _GOSSIPMESSAGE_CONTENTTYPE._serialized_end=441
  _NETWORKACKNOWLEDGEMENT._serialized_start=443
  _NETWORKACKNOWLEDGEMENT._serialized_end=562
  _NETWORKACKNOWLEDGEMENT_STATUS._serialized_start=517
  _NETWORKACKNOWLEDGEMENT_STATUS._serialized_end=562
  _GOSSIPBLOCKREQUEST._serialized_start=564
  _GOSSIPBLOCKREQUEST._serialized_end=639
  _GOSSIPBLOCKRESPONSE._serialized_start=641
  _GOSSIPBLOCKRESPONSE._serialized_end=679
  _GOSSIPBATCHRESPONSE._serialized_start=681
  _GOSSIPBATCHRESPONSE._serialized_end=719
  _GOSSIPBATCHBYBATCHIDREQUEST._serialized_start=721
  _GOSSIPBATCHBYBATCHIDREQUEST._serialized_end=799
  _GOSSIPBATCHBYTRANSACTIONIDREQUEST._serialized_start=801
  _GOSSIPBATCHBYTRANSACTIONIDREQUEST._serialized_end=886
# @@protoc_insertion_point(module_scope)
