# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import transaction_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3python/sawtooth_block_info/protobuf/processor.proto\x1a\x35python/sawtooth_block_info/protobuf/transaction.proto\"\x95\x02\n\x11TpRegisterRequest\x12\x0e\n\x06\x66\x61mily\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nnamespaces\x18\x04 \x03(\t\x12\x15\n\rmax_occupancy\x18\x05 \x01(\r\x12\x18\n\x10protocol_version\x18\x06 \x01(\r\x12L\n\x14request_header_style\x18\x07 \x01(\x0e\x32..TpRegisterRequest.TpProcessRequestHeaderStyle\"L\n\x1bTpProcessRequestHeaderStyle\x12\x16\n\x12HEADER_STYLE_UNSET\x10\x00\x12\x0c\n\x08\x45XPANDED\x10\x01\x12\x07\n\x03RAW\x10\x02\"\x89\x01\n\x12TpRegisterResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.TpRegisterResponse.Status\x12\x18\n\x10protocol_version\x18\x02 \x01(\r\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x15\n\x13TpUnregisterRequest\"s\n\x14TpUnregisterResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.TpUnregisterResponse.Status\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x84\x01\n\x10TpProcessRequest\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.TransactionHeader\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x12\n\ncontext_id\x18\x04 \x01(\t\x12\x14\n\x0cheader_bytes\x18\x05 \x01(\x0c\"\xb7\x01\n\x11TpProcessResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.TpProcessResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rextended_data\x18\x03 \x01(\x0c\"O\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x17\n\x13INVALID_TRANSACTION\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x42(\n\x15sawtooth.sdk.protobufP\x01Z\rprocessor_pb2b\x06proto3')



_TPREGISTERREQUEST = DESCRIPTOR.message_types_by_name['TpRegisterRequest']
_TPREGISTERRESPONSE = DESCRIPTOR.message_types_by_name['TpRegisterResponse']
_TPUNREGISTERREQUEST = DESCRIPTOR.message_types_by_name['TpUnregisterRequest']
_TPUNREGISTERRESPONSE = DESCRIPTOR.message_types_by_name['TpUnregisterResponse']
_TPPROCESSREQUEST = DESCRIPTOR.message_types_by_name['TpProcessRequest']
_TPPROCESSRESPONSE = DESCRIPTOR.message_types_by_name['TpProcessResponse']
_TPREGISTERREQUEST_TPPROCESSREQUESTHEADERSTYLE = _TPREGISTERREQUEST.enum_types_by_name['TpProcessRequestHeaderStyle']
_TPREGISTERRESPONSE_STATUS = _TPREGISTERRESPONSE.enum_types_by_name['Status']
_TPUNREGISTERRESPONSE_STATUS = _TPUNREGISTERRESPONSE.enum_types_by_name['Status']
_TPPROCESSRESPONSE_STATUS = _TPPROCESSRESPONSE.enum_types_by_name['Status']
TpRegisterRequest = _reflection.GeneratedProtocolMessageType('TpRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _TPREGISTERREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpRegisterRequest)
  })
_sym_db.RegisterMessage(TpRegisterRequest)

TpRegisterResponse = _reflection.GeneratedProtocolMessageType('TpRegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _TPREGISTERRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpRegisterResponse)
  })
_sym_db.RegisterMessage(TpRegisterResponse)

TpUnregisterRequest = _reflection.GeneratedProtocolMessageType('TpUnregisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _TPUNREGISTERREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpUnregisterRequest)
  })
_sym_db.RegisterMessage(TpUnregisterRequest)

TpUnregisterResponse = _reflection.GeneratedProtocolMessageType('TpUnregisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _TPUNREGISTERRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpUnregisterResponse)
  })
_sym_db.RegisterMessage(TpUnregisterResponse)

TpProcessRequest = _reflection.GeneratedProtocolMessageType('TpProcessRequest', (_message.Message,), {
  'DESCRIPTOR' : _TPPROCESSREQUEST,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpProcessRequest)
  })
_sym_db.RegisterMessage(TpProcessRequest)

TpProcessResponse = _reflection.GeneratedProtocolMessageType('TpProcessResponse', (_message.Message,), {
  'DESCRIPTOR' : _TPPROCESSRESPONSE,
  '__module__' : 'python.sawtooth_block_info.protobuf.processor_pb2'
  # @@protoc_insertion_point(class_scope:TpProcessResponse)
  })
_sym_db.RegisterMessage(TpProcessResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\rprocessor_pb2'
  _TPREGISTERREQUEST._serialized_start=111
  _TPREGISTERREQUEST._serialized_end=388
  _TPREGISTERREQUEST_TPPROCESSREQUESTHEADERSTYLE._serialized_start=312
  _TPREGISTERREQUEST_TPPROCESSREQUESTHEADERSTYLE._serialized_end=388
  _TPREGISTERRESPONSE._serialized_start=391
  _TPREGISTERRESPONSE._serialized_end=528
  _TPREGISTERRESPONSE_STATUS._serialized_start=483
  _TPREGISTERRESPONSE_STATUS._serialized_end=528
  _TPUNREGISTERREQUEST._serialized_start=530
  _TPUNREGISTERREQUEST._serialized_end=551
  _TPUNREGISTERRESPONSE._serialized_start=553
  _TPUNREGISTERRESPONSE._serialized_end=668
  _TPUNREGISTERRESPONSE_STATUS._serialized_start=483
  _TPUNREGISTERRESPONSE_STATUS._serialized_end=528
  _TPPROCESSREQUEST._serialized_start=671
  _TPPROCESSREQUEST._serialized_end=803
  _TPPROCESSRESPONSE._serialized_start=806
  _TPPROCESSRESPONSE._serialized_end=989
  _TPPROCESSRESPONSE_STATUS._serialized_start=910
  _TPPROCESSRESPONSE_STATUS._serialized_end=989
# @@protoc_insertion_point(module_scope)
