# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/setting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1python/sawtooth_block_info/protobuf/setting.proto\"O\n\x07Setting\x12\x1f\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0e.Setting.Entry\x1a#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB&\n\x15sawtooth.sdk.protobufP\x01Z\x0bsetting_pb2b\x06proto3')



_SETTING = DESCRIPTOR.message_types_by_name['Setting']
_SETTING_ENTRY = _SETTING.nested_types_by_name['Entry']
Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), {

  'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
    'DESCRIPTOR' : _SETTING_ENTRY,
    '__module__' : 'python.sawtooth_block_info.protobuf.setting_pb2'
    # @@protoc_insertion_point(class_scope:Setting.Entry)
    })
  ,
  'DESCRIPTOR' : _SETTING,
  '__module__' : 'python.sawtooth_block_info.protobuf.setting_pb2'
  # @@protoc_insertion_point(class_scope:Setting)
  })
_sym_db.RegisterMessage(Setting)
_sym_db.RegisterMessage(Setting.Entry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\013setting_pb2'
  _SETTING._serialized_start=53
  _SETTING._serialized_end=132
  _SETTING_ENTRY._serialized_start=97
  _SETTING_ENTRY._serialized_end=132
# @@protoc_insertion_point(module_scope)
