# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5python/sawtooth_block_info/protobuf/transaction.proto\"\xd5\x01\n\x11TransactionHeader\x12\x1a\n\x12\x62\x61tcher_public_key\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x02 \x03(\t\x12\x13\n\x0b\x66\x61mily_name\x18\x03 \x01(\t\x12\x16\n\x0e\x66\x61mily_version\x18\x04 \x01(\t\x12\x0e\n\x06inputs\x18\x05 \x03(\t\x12\r\n\x05nonce\x18\x06 \x01(\t\x12\x0f\n\x07outputs\x18\x07 \x03(\t\x12\x16\n\x0epayload_sha512\x18\t \x01(\t\x12\x19\n\x11signer_public_key\x18\n \x01(\t\"H\n\x0bTransaction\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x18\n\x10header_signature\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"5\n\x0fTransactionList\x12\"\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x0c.TransactionB*\n\x15sawtooth.sdk.protobufP\x01Z\x0ftransaction_pb2b\x06proto3')



_TRANSACTIONHEADER = DESCRIPTOR.message_types_by_name['TransactionHeader']
_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_TRANSACTIONLIST = DESCRIPTOR.message_types_by_name['TransactionList']
TransactionHeader = _reflection.GeneratedProtocolMessageType('TransactionHeader', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONHEADER,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_pb2'
  # @@protoc_insertion_point(class_scope:TransactionHeader)
  })
_sym_db.RegisterMessage(TransactionHeader)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_pb2'
  # @@protoc_insertion_point(class_scope:Transaction)
  })
_sym_db.RegisterMessage(Transaction)

TransactionList = _reflection.GeneratedProtocolMessageType('TransactionList', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONLIST,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_pb2'
  # @@protoc_insertion_point(class_scope:TransactionList)
  })
_sym_db.RegisterMessage(TransactionList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\017transaction_pb2'
  _TRANSACTIONHEADER._serialized_start=58
  _TRANSACTIONHEADER._serialized_end=271
  _TRANSACTION._serialized_start=273
  _TRANSACTION._serialized_end=345
  _TRANSACTIONLIST._serialized_start=347
  _TRANSACTIONLIST._serialized_end=400
# @@protoc_insertion_point(module_scope)
