# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/transaction_receipt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python.sawtooth_block_info.protobuf import events_pb2 as python_dot_sawtooth__block__info_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=python/sawtooth_block_info/protobuf/transaction_receipt.proto\x1a\x30python/sawtooth_block_info/protobuf/events.proto\"w\n\x12TransactionReceipt\x12#\n\rstate_changes\x18\x01 \x03(\x0b\x32\x0c.StateChange\x12\x16\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x06.Event\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x0c\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\"{\n\x0bStateChange\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x1f\n\x04type\x18\x03 \x01(\x0e\x32\x11.StateChange.Type\"+\n\x04Type\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x07\n\x03SET\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\"6\n\x0fStateChangeList\x12#\n\rstate_changes\x18\x01 \x03(\x0b\x32\x0c.StateChangeB*\n\x15sawtooth.sdk.protobufP\x01Z\x0ftxn_receipt_pb2b\x06proto3')



_TRANSACTIONRECEIPT = DESCRIPTOR.message_types_by_name['TransactionReceipt']
_STATECHANGE = DESCRIPTOR.message_types_by_name['StateChange']
_STATECHANGELIST = DESCRIPTOR.message_types_by_name['StateChangeList']
_STATECHANGE_TYPE = _STATECHANGE.enum_types_by_name['Type']
TransactionReceipt = _reflection.GeneratedProtocolMessageType('TransactionReceipt', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONRECEIPT,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_receipt_pb2'
  # @@protoc_insertion_point(class_scope:TransactionReceipt)
  })
_sym_db.RegisterMessage(TransactionReceipt)

StateChange = _reflection.GeneratedProtocolMessageType('StateChange', (_message.Message,), {
  'DESCRIPTOR' : _STATECHANGE,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_receipt_pb2'
  # @@protoc_insertion_point(class_scope:StateChange)
  })
_sym_db.RegisterMessage(StateChange)

StateChangeList = _reflection.GeneratedProtocolMessageType('StateChangeList', (_message.Message,), {
  'DESCRIPTOR' : _STATECHANGELIST,
  '__module__' : 'python.sawtooth_block_info.protobuf.transaction_receipt_pb2'
  # @@protoc_insertion_point(class_scope:StateChangeList)
  })
_sym_db.RegisterMessage(StateChangeList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\017txn_receipt_pb2'
  _TRANSACTIONRECEIPT._serialized_start=115
  _TRANSACTIONRECEIPT._serialized_end=234
  _STATECHANGE._serialized_start=236
  _STATECHANGE._serialized_end=359
  _STATECHANGE_TYPE._serialized_start=316
  _STATECHANGE_TYPE._serialized_end=359
  _STATECHANGELIST._serialized_start=361
  _STATECHANGELIST._serialized_end=415
# @@protoc_insertion_point(module_scope)
